#!/bin/bash
clear
echo "========================"
echo "    GLOBAL HELP MENU"
echo "========================"
echo ""
echo "[NAVIGATION]"
echo "  cd [folder]   - Change directory"
echo "  cd ..         - Go up one directory level"
echo "  ls            - List files in the current directory"
echo ""
echo "[FILE OPERATIONS]"
echo "  echo TEXT > file.txt    - Create file.txt with TEXT"
echo "  cat file.txt            - Display contents of file.txt"
echo "  rm file.txt             - Delete file.txt"
echo "  mv old.txt new.txt      - Rename a file"
echo "  cp file.txt folder/     - Copy file to a folder"
echo "  mv file.txt folder/     - Move file to a folder"
echo ""
echo "[OTHER TIPS]"
echo "  man command  - Displays info about a specific command"
echo "  command --help  - Another way to see command usage details"
echo "  clear        - Clear screen"
echo "  exit         - Close the terminal (quit game)"
echo ""
read -p "Press Enter to return to the game..."
